name: "Bug report"
description: "Report a reproducible bug in data-context"
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the form below as completely as possible to help us reproduce and fix the issue quickly.
  - type: checkboxes
    id: duplicates
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the problem you’re experiencing.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    id: version
    attributes:
      label: data-context version
      description: Output of `npm ls data-context` or the version from package.json.
      placeholder: "e.g. 2.0.0"
    validations:
      required: true
  - type: input
    id: node
    attributes:
      label: Node.js version
      placeholder: "e.g. v18.20.3, v20.16.0"
  - type: input
    id: browser
    attributes:
      label: Browser and version (if applicable)
      placeholder: "e.g. Chrome 128, Firefox 127"
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "e.g. Windows 11, macOS 14.5, Ubuntu 24.04"
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "What happened? What did you expect to happen?"
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to reproduce
      description: Provide exact steps to reproduce the issue.
      placeholder: |
        1. Using code snippet below
        2. Run `node index.test.js`
        3. Observe error message...
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Minimal reproducible code
      description: Provide a minimal snippet (no external deps) that reproduces the issue.
      render: javascript
      placeholder: |
        const DC = require('data-context');
        const { parse, createDataContext } = DC;
        const ctx = parse('{"count":0}', createDataContext);
        // ...
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: "What should have happened?"
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: "What actually happened?"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / stack trace
      render: text
      placeholder: "Paste relevant logs or stack traces here."
  - type: textarea
    id: extras
    attributes:
      label: Additional context / screenshots
      placeholder: "Anything else relevant to the issue."
  - type: checkboxes
    id: contribution
    attributes:
      label: Are you willing to submit a PR?
      options:
        - label: Yes, I’m willing to submit a PR to fix this