name: "Question"
description: "Ask a question about using data-context"
title: "[Question]: "
labels: ["question"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Please provide enough context so we can help quickly. If this is a bug, use the Bug report template instead.
  - type: input
    id: version
    attributes:
      label: data-context version
      placeholder: "e.g. 2.0.0"
  - type: textarea
    id: question
    attributes:
      label: Your question
      placeholder: "Describe what you need help with."
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Relevant code snippet
      render: javascript
      placeholder: |
        const DC = require('data-context');
        // ...
  - type: input
    id: runtime
    attributes:
      label: Runtime environment
      description: "Node.js version and/or Browser + version"
      placeholder: "e.g. Node v20.16.0; Chrome 128"
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "e.g. Windows 11, macOS 14.5, Ubuntu 24.04"
  - type: textarea
    id: extras
    attributes:
      label: Additional context
      placeholder: "Anything else you want to add."